import Footer from "@/components/footer";
import "./globals.css";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/toaster";
import { createClient } from "@/lib/supabase/server";
import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "CMS",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en" className={`${GeistSans.variable} h-full`}>
      <body className="flex min-h-full flex-col bg-background text-foreground">
        <div className="flex flex-col min-h-screen">
          {/* Header - sticky on desktop, fixed on mobile */}
          {user && (
            <div className="sticky top-0 z-50 w-full">
              <Header />
            </div>
          )}

          {/* Main content area */}
          <main className="flex-grow w-full bg-gray-200 px-2 sm:px-4 md:px-6">
            <div className="max-w-screen-2xl mx-auto w-full">{children}</div>
          </main>

          {/* Footer */}
          {user && (
            <div className="mt-auto w-full">
              <Footer />
            </div>
          )}
        </div>

        {/* Toast notifications */}
        <Toaster />
      </body>
    </html>
  );
}
